// <auto-generated />
using System;
using ComplianceMonitor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComplianceMonitor.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ComplianceDbContext))]
    [Migration("20261004040430_DecisionAuditBackfill")]
    partial class DecisionAuditBackfill
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("ComplianceMonitor.Infrastructure.Persistence.Entities.AnalysisEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<double?>("ConfidenceThreshold")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionReason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionSource")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Guideline")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelProvider")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelTopResult")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<double?>("ModelTopScore")
                        .HasColumnType("REAL");

                    b.Property<string>("RawScoresJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Strategy")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Result", "CreatedAt");

                    b.ToTable("Analyses", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
