using System.Globalization;
using System.Text;
using ComplianceMonitor.Application.Compliance.Models;

namespace ComplianceMonitor.LabelLab;

/// <summary>Renders results as Markdown; the same text goes to the console and to docs/label-tuning.md.</summary>
public static class MarkdownReport
{
    private const int MaxActionLength = 48;

    public static string Render(IReadOnlyList<StrategyReport> reports, string model, double confidenceFloor, DateTimeOffset generatedAt)
    {
        ArgumentNullException.ThrowIfNull(reports);
        var md = new StringBuilder();
        var inv = CultureInfo.InvariantCulture;

        md.AppendLine("# Label tuning");
        md.AppendLine();
        md.AppendLine(inv, $"Generated by `tools/LabelLab` at {generatedAt.UtcDateTime:yyyy-MM-ddTHH:mm:ssZ}. Do not edit by hand.");
        md.AppendLine(inv, $"Model `{model}`, confidence threshold {confidenceFloor:0.00}. Cases in `tools/LabelLab/cases.json`.");
        md.AppendLine();
        md.AppendLine("| Strategy | Brief cases | Extra cases |");
        md.AppendLine("|----------|-------------|-------------|");
        foreach (var report in reports)
        {
            md.AppendLine(inv, $"| {report.Strategy} | {Accuracy(report, brief: true)} | {Accuracy(report, brief: false)} |");
        }

        foreach (var report in reports)
        {
            md.AppendLine();
            md.AppendLine(inv, $"## {report.Strategy}");
            md.AppendLine();
            md.AppendLine("| # | Case | Expected | Predicted | Decided by | Model | Top score | Margin | Result |");
            md.AppendLine("|---|------|----------|-----------|------------|-------|-----------|--------|--------|");
            foreach (var r in report.Results)
            {
                var label = (r.Case.Brief ? "**brief** " : "") + Truncate(r.Case.Action);
                var outcome = r.Error is not null ? $"ERROR: {r.Error}" : r.Passed ? "pass" : "FAIL";
                md.AppendLine(inv,
                    $"| {r.Number} | {Escape(label)} | {Name(r.Case.Expected)} | {Name(r.Predicted)} | {Name(r.Reason)} " +
                    $"| {Name(r.ModelResult)} | {Score(r.TopScore)} | {Score(r.Margin)} | {Escape(outcome)} |");
            }

            md.AppendLine();
            md.AppendLine(inv, $"Accuracy: brief {Accuracy(report, brief: true)}, extra {Accuracy(report, brief: false)}.");
        }

        return md.ToString();
    }

    public static string Accuracy(StrategyReport report, bool brief)
    {
        ArgumentNullException.ThrowIfNull(report);
        var subset = report.Results.Where(r => r.Case.Brief == brief).ToList();
        if (subset.Count == 0)
        {
            return "n/a";
        }

        var passed = subset.Count(r => r.Passed);
        return string.Create(CultureInfo.InvariantCulture, $"{passed}/{subset.Count} ({100.0 * passed / subset.Count:0}%)");
    }

    private static string Name(ComplianceResult? value) => value switch
    {
        ComplianceResult.Complies => "COMPLIES",
        ComplianceResult.Deviates => "DEVIATES",
        ComplianceResult.Unclear => "UNCLEAR",
        _ => "—",
    };

    private static string Name(DecisionReason? value) => value switch
    {
        DecisionReason.ModelClassification => "MODEL",
        DecisionReason.NoApplicableGuideline => "RULE: no guideline",
        DecisionReason.MissingTemporalEvidence => "RULE: no frequency evidence",
        DecisionReason.InsufficientModelConfidence => "RULE: low confidence",
        _ => "—",
    };

    private static string Score(double? value) =>
        value is { } v ? v.ToString("0.000", CultureInfo.InvariantCulture) : "—";

    private static string Truncate(string text) =>
        text.Length <= MaxActionLength ? text : string.Concat(text.AsSpan(0, MaxActionLength - 1), "…");

    private static string Escape(string text) => text.Replace("|", "\\|", StringComparison.Ordinal);
}
